Load modules

In [1]:
import numpy as np
import pandas as pd

# Our modules
from utils.minmax_hart_norm import minmax_hart_convert, minmax_hart_revert

csv file load

In [2]:
csv_file = pd.read_csv('train_y_wh.csv')
csv_arr = csv_file.to_numpy()[0, :-2]

print(csv_arr.shape)

(68,)


In [3]:
width = csv_file.to_numpy()[0, -2, np.newaxis]
height = csv_file.to_numpy()[0, -1, np.newaxis]

print(width.shape)
print(height.shape)

(1,)
(1,)


Convert

In [5]:
converted_arr, mat_calc, df_y = minmax_hart_convert(csv_arr, width, height, parm=None, noise=False)

(68,)


array([ 0.06546284, -0.23070818, -0.1125837 , -0.16558854, -0.05893323,
        0.13568152,  0.06214448,  0.17653288, -0.18064749,  0.02801802,
       -0.06783019,  0.07144346, -0.04256996,  0.09547921,  0.18270138,
        0.01607231, -0.00400473,  0.12617847, -0.06100479,  0.0285133 ,
        0.07293035,  0.11603922, -0.1243896 ,  0.00494212, -0.04238596,
       -0.00191631,  0.00571505,  0.0008032 ,  0.01159747,  0.10407756,
       -0.09549612, -0.27349852, -0.12787617, -0.14185976,  0.13517045,
        0.06176189, -0.04274016,  0.10657734, -0.10711338,  0.0696156 ,
        0.07381405, -0.03950504, -0.00395057, -0.14289049,  0.1496814 ,
        0.01670613,  0.11617105, -0.02332056, -0.01303029, -0.068032  ,
        0.14935808,  0.09312398, -0.18760196, -0.01058317, -0.03496906,
        0.10869426,  0.05732641,  0.08093211,  0.00882736, -0.15100612,
        0.02512247, -0.03786635, -0.04138939, -0.01983786,  0.14119714,
       -0.19352814,  0.09130404,  0.05894403])

In [5]:
type(mat_calc)

numpy.ndarray

Revert

In [6]:
reverted_arr = minmax_hart_revert(converted_arr, mat_calc, width, height)

(68,)


In [7]:
reverted_arr

array([1269.,  774.,  817.,  857.,  656., 1002.,  916., 1020.,  639.,
       1159.,  711., 1090., 1175.,  990., 1283., 1140.,  963., 1149.,
       1267., 1195., 1293., 1271., 1232., 1204., 1283., 1360., 1273.,
       1368., 1216., 1483., 1263., 1444., 1228., 1495., 1234., 1607.,
       1212., 1648., 1183., 1656.,  737., 1401., 1059., 1312., 1065.,
       1358., 1328.,  664., 1316.,  841., 1438., 1104., 1336., 1206.,
       1354., 1289., 1371., 1338., 1310., 1395., 1364., 1476., 1307.,
       1517., 1299., 1617., 1257., 1690.])

---
확인

In [8]:
print(np.max((reverted_arr - csv_arr)))
print(np.min((reverted_arr - csv_arr)))

2.2737367544323206e-13
0.0


In [9]:
print(np.max((reverted_arr)))
print(np.min((reverted_arr)))
print(np.max((csv_arr)))
print(np.min((csv_arr)))

1690.0000000000002
639.0
1690.0
639.0


In [10]:
reverted_arr_2 = np.concatenate((reverted_arr, width, height), axis=0)
df_y2 = np.concatenate((df_y, width, height), axis=0)

print(reverted_arr_2.shape)

(70,)


In [11]:
reverted_arr_2

array([1269.,  774.,  817.,  857.,  656., 1002.,  916., 1020.,  639.,
       1159.,  711., 1090., 1175.,  990., 1283., 1140.,  963., 1149.,
       1267., 1195., 1293., 1271., 1232., 1204., 1283., 1360., 1273.,
       1368., 1216., 1483., 1263., 1444., 1228., 1495., 1234., 1607.,
       1212., 1648., 1183., 1656.,  737., 1401., 1059., 1312., 1065.,
       1358., 1328.,  664., 1316.,  841., 1438., 1104., 1336., 1206.,
       1354., 1289., 1371., 1338., 1310., 1395., 1364., 1476., 1307.,
       1517., 1299., 1617., 1257., 1690., 2010., 1670.])

---
한번에 변환

In [12]:
x_arr = []
y_arr = []


for i in range(len(csv_file)):
# for i in range(5):
    csv_arr = csv_file.to_numpy()[i, :-2]
    converted_arr, mat_calc, df_y = minmax_hart_convert(csv_arr, width, height, parm = None)
    
    x_arr.append(converted_arr)
    y_arr.append(df_y)
    
a = pd.DataFrame(np.array(x_arr))
b = pd.DataFrame(np.array(y_arr))

a.columns = csv_file.columns[:-2]
b.columns = csv_file.columns[:-2]

a.to_csv('./train_x_wh_hart.csv', index=False)
b.to_csv('./train_y_wh_hart.csv', index=False)

np.save('./mat_calc.npy', mat_calc)